### ISSUE TITLE
[docs] Updated github/private key working example for OSX

### ISSUE THREAD

**Issue by rosskevin** [cloud66/habitus#28]
I spent some time figuring this out so I hope it can help others or be added to examples.

1.  `Dockerfile`
  ```
FROM ubuntu
RUN apt-get update && apt-get install -y wget openssh-client

# add the authorized host key for github (avoids "Host key verification failed")
RUN mkdir ~/.ssh && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

ARG host
ENV PRIVATE_KEY /root/.ssh/id_rsa
RUN wget -O $PRIVATE_KEY http://$host:8080/v1/secrets/file/id_rsa \
    && chmod 0600 $PRIVATE_KEY \
    && ssh -T git@github.com \
    && rm $PRIVATE_KEY
  ```

2. `build.yml`
  ```yaml
build:
  version: 2016-03-14
  steps:
    builder:
      name: builder
      dockerfile: Dockerfile
      secrets:
        id_rsa:
          type: file
          value: _env(HOME)/.ssh/id_rsa
  ```

3. Run it (OSX command line)
  ```bash
habitus --build host=$(ipconfig getifaddr en0) --host unix:///var/run/docker.sock --binding=0.0.0.0
  ```
