### ISSUE TITLE
Unwanted Images

### ISSUE THREAD

**Issue by alledm** [cloud66/habitus#29]
hello, I have a simple setup like the following

```
build:
  version: 2016-03-14 # version of the build schema.
  steps:
    builder:
      name: b.gcr.io/test/go_base:_env(GIT_LABEL)
      dockerfile: Dockerfile.go_base
      artifacts:
        - /comp3
        - /comp2
        - /comp1
    comp3:
      name: b.gcr.io/test/comp3:_env(GIT_LABEL)
      dockerfile: Dockerfile.comp3
      depends_on:
        - builder
    comp2:
      name: b.gcr.io/test/comp2:_env(GIT_LABEL)
      dockerfile: Dockerfile.comp2
      depends_on:
        - builder
    comp1:
      name: b.gcr.io/test/comp1:_env(GIT_LABEL)
      dockerfile: Dockerfile.comp1
      depends_on:
        - builder
```

with a sample Dockerfile.comp1 as simple as:
```
FROM ubuntu
ADD ./comp1 /comp1
CMD ["/comp1", "--config", "/configs.yml"]
```
When I run habitus, the images are always removed:
```
2016/10/11 16:33:20 ▶ Removing unwanted image b.gcr.io/test/comp1:fix_test-ademaria 
2016/10/11 16:33:20 ▶ Removing unwanted image b.gcr.io/test/comp2:fix_test-ademaria 
2016/10/11 16:33:20 ▶ Removing unwanted image b.gcr.io/test/comp3:fix_test-ademaria 

```
How can I tell habitus that I want to keep an image?
How do I push it to a repository once built?
