### ISSUE TITLE
ENTRYPOINT + CMD not working

### ISSUE THREAD

**Issue by alledm** [cloud66/habitus#30]
hello, I have a simple setup like the following

```
build:
  version: 2016-03-14 # version of the build schema.
  steps:
    builder:
      name: b.gcr.io/test/go_base:_env(GIT_LABEL)
      dockerfile: Dockerfile.go_base
      artifacts:
        - /comp3
        - /comp2
        - /comp1
    comp3:
      name: b.gcr.io/test/comp3:_env(GIT_LABEL)
      dockerfile: Dockerfile.comp3
      depends_on:
        - builder
    comp2:
      name: b.gcr.io/test/comp2:_env(GIT_LABEL)
      dockerfile: Dockerfile.comp2
      depends_on:
        - builder
    comp1:
      name: b.gcr.io/test/comp1:_env(GIT_LABEL)
      dockerfile: Dockerfile.comp1
      depends_on:
        - builder
```

with a sample Dockerfile.comp1 as simple as:
```
FROM ubuntu
ADD /artifacts/comp1 /comp1
ENTRYPOINT ["/comp1"]
CMD ["--config", "/configs.yml"]

```
When I run **`habitus`**, I get the following error
```
2016/10/11 16:36:41 ▶ Build for step b.gcr.io/test/comp1:fix_test-ademaria failed due to Unknown flag: config
```
