### ISSUE TITLE
Relative build.yml and Dockerfile paths not generating the Dockerfile.generated at the right location

### ISSUE THREAD

**Issue by chdeliens** [cloud66/habitus#45]
Having the following (simplified) build.yml:
```
build:
  version: 2016-03-14
  steps:
    builder:
      name: builder
      dockerfile: builder/Dockerfile
```

And when using the following command:
`sudo habitus --host=unix:///var/run/docker.sock --binding=127.0.0.1 --keep-all --no-cache -f builder/build.yml` (and probably a simpler version of it as well, didn't try out)

the following occurs:
```
2017/01/06 17:00:49 ▶ Using 'builder/build.yml' as build file 
2017/01/06 17:00:49 ▶ Collecting artifact information 
2017/01/06 17:00:49 ▶ Building 2 steps 
2017/01/06 17:00:49 ▶ Starting API on 8080 
2017/01/06 17:00:49 ▶ Step 0 - builder: builder 
2017/01/06 17:00:49 ▶ Step 1 - app-base: app-base 
2017/01/06 17:00:49 ▶ Parallel build for builder 
2017/01/06 17:00:49 ▶ Building builder 
2017/01/06 17:00:49 ▶ Parsing and converting 'builder/Dockerfile' 
2017/01/06 17:00:49 ▶ Writing the new Dockerfile into builder/Dockerfile.generated 
2017/01/06 17:00:49 ▶ Building the builder image from Dockerfile.generated 
2017/01/06 17:00:49 ▶ Build for step builder failed due to API error (500): {"message":"Cannot locate specified Dockerfile: Dockerfile.generated"}
```

We can clearly see in the above log that Habitus is writing to `builder/Dockerfile.generated` but then tries to read from `Dockerfile.generated` instead.

Being able to run Habitus from a parent directory using the `-f` argument would allow to share resources (like configuration files) in a common top-level folder.

**Comment by kamerblauwlicht** [comment]
thanks for the bug report @chdeliens

**Comment by kamerblauwlicht** [comment]
@chdeliens I found the issue with your example, because your `build.yml` is in the `builder` directory you need to change your `build.yml` to the following example and it works:

```
build:
  version: 2016-03-14
  steps:
    builder:
      name: builder
      dockerfile: Dockerfile
```

**-f** is telling to use `builder/build.yml` but you at the moment it's using `/builder` as the reference, you don't need to prefix the Dockerfile with the `/builder` directory.

**Comment by OrenRysn** [comment]
Related issue, not sure if it should be a new issue.

Wanted to have individual Dockerfiles exist in their own subdirectories, so they could all keep the name "Dockerfile" rather than be "Dockerfile.<something>". This allows for syntax highlighting of the Dockerfiles in editors like PyCharm and Sublime Text.

However, if I have the following directory structure:

> .
> ├── build.yml
> ├── mf_builder
> │   ├── Dockerfile
> │   └── Dockerfile.generated
> ├── run.sh
> ├── scripts
> │   ├── cloneRepos.sh
> │   ├── installruby.sh
> │   ├── installruby_docker.sh.bak
> │   └── ucplayer_build.py
> └── ucplayer_builder
>     └── Dockerfile

And build.yml:
```
build:
  version: 2016-03-14 # version of the build schema.
  steps:
    mf_builder:
      name: mf_builder
      dockerfile: mf_builder/Dockerfile
    ucplayer_builder:
      name: ucplayer_builder
      dockerfile: ucplayer_builder/Dockerfile
      depends_on:
        - mf_builder
      secrets:
        id_rsa:
          type: file
          value: _env(HOME)/.ssh/id_rsa

```

I end up with an issue similar to @chdeliens.

Was wondering if Habitus can already support this directory structure, perhaps with some changes to the build.yml or having separate build.yml files with each Dockerfile, or if I must stick with one build.yml in the same directory as all Dockerfiles.
