### ISSUE TITLE
Update artifacts copyToHost() to support directories

### ISSUE THREAD

**Issue by wagoodman** [cloud66/habitus#48]
It would be nice to declare a directory of artifacts (such as a ruby bundle directory) instead of listing all files explicitly... for instance:
```
build:
  version: 2016-03-14
  steps:
    builder:
      name: myapp/builder
      dockerfile: Dockerfile
      artifacts:
        - /bundler
....
```
where `/bundler` contains sub directories:
```
bin  build_info  bundler  cache  doc  extensions  gems	specifications
```
and those sub directories have files... etc.
