### ISSUE TITLE
Ability to access network during build

### ISSUE THREAD

**Issue by neverfox** [cloud66/habitus#80]
Docker build now supports a --network flag that can, for example, let you access docker-compose services running on the host in your build (similar to how you can access the habitus server). Is it or would it be possible to have access to that through a habitus parameter?

**Comment by khash** [comment]
Thank you @neverfox  

I think this can definitely be a possible forward as long as it's not only limited to compose (habitus uses Docker daemon directly)

**Comment by mumoshu** [comment]
Hi!

Indeed it isn't docker-compose specific. Actually, I had been [suggested by a moby maintainer to try it](https://github.com/moby/moby/pull/36443#pullrequestreview-100720880) for a secure secret injection to build context.

Implemtation-wise, would introducing a `network` key in `build.yaml` would be ok?

Like:

```yaml
build:
  version: 2016-03-14
  steps:
    test:
      name: test
      dockerfile: Dockerfile
      network: myprivatenet
```
