### ISSUE TITLE
[Feature Request] Setting habitus' args from within build.yml

### ISSUE THREAD

**Issue by mumoshu** [cloud66/habitus#87]
Extracted from https://github.com/cloud66/habitus/issues/74#issuecomment-371414652

```yaml
# NEW: matches to habitus -secret=true -host=192.168.99.1 -binding 192.168.99.1
# But this should be a separate feature request 
secrets: true
host: 192.168.99.1
binding: 192.168.99.1

build:
  version: 2016-03-14 # version of the build schema.
  steps:
  # snip
```

In this specific example, `secrets`, `host` and `binding` would possibly serve as a sane defaults possibly used across your colleagues' local machines.

`host` and `binding` would be overrode via command-line flags when habitus is being run in e.g. your CI builds with a docker setup different than local one.
