### ISSUE TITLE
[Feature request] Support for docker's multi-stage build

### ISSUE THREAD

**Issue by mumoshu** [cloud66/habitus#89]
## Context

I have been using this [lengthy bash script](https://gist.github.com/mumoshu/e8dc1f3c98e06a97fe2d7df57032f07b#file-dockerbuild-sh-L82) for caching both the builder image and the runtime image, while exploiting build-args to safely pass secrets from local workdir to build context.

## Problem

In comparison to habitus, docker's multi-stage build has a benefit of (in theory) faster assets propagation across stages by not leveraging `docker cp` like habitus do.

However, as we already know, we don't have a well-establish way to safely pass secrets from local worktree to a build context out-of-box in docker. [This is where habitus really shines](https://github.com/moby/moby/issues/13490#issuecomment-372537941).

// Of course habitus adds much regarding reproducible build and support for more complex workflows, and so on. Great job 😄But please let me focus on the aspect of the "secret management & faster build".

Can we somehow improve habitus to rely docker's multi-stage build for faster asset propagation while retaining the support for secrets?

## Suggestion

My suggestion is to add support for `--target` option of `docker build` to match single habitus step to a corresponding docker-build targeted to an intermediate image of a multi-stage build.

An example `build.yml` would look like the below. Notice the same Dockerfile is specified for both `builder` and `runtime` step, but the `target` is differentiated.

```yaml
build:
  version: 2016-03-14 # version of the build schema.
  steps:
    builder:
      name: builder
      dockerfile: Dockerfile
      target: builder
    runtime:
      name: runtime
      dockerfile: Dockerfile
      target: runtime
      depends_on:
      - builder
```

```
FROM builder-base AS builder
ADD . /src
WORKDIR /src
RUN build/binary/with/deps/from/private/github/repos

FROM runtime-base
COPY --from=builder /build/assets/mycmd /bin/mycmd
ENTRYPOINT ["/bin/mycmd"]
```

This way, habitus would work as exactly before, but utilizing docker's multi-stage build to pass assets around.

**Comment by mumoshu** [comment]
Just for clarification - why would I need two steps? Can't I write build.yml like:

```yaml
build:
  version: 2016-03-14 # version of the build schema.
  steps:
    runtime:
      name: runtime
      dockerfile: Dockerfile
```

so that it will trigger a multi-stage build with the exact same output?

The answer is yes, and no.

It works, but am now unable to `docker-push` the intermediate `builder` image.

You basically need to run `docker build --target foo -t myimg-foo:$VER` to tag the intermediate image for `docker-push`. The docker-push is required in order to use the external docker registry as the global cache of the intermediate image. And it is, IHMO, a common pattern seen in CI/CD env.
